# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
spec:
  selector:
    matchLabels:
      app: gitops-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
        - name: gitops-demo
          image: davarski/gitops-demo:0.0.4
          ports:
            - containerPort: 80

