apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: helm
    repoURL: https://github.com/adavarski/ArgoCD-GitOps-playground
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
