apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-prod-cluster
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: kind-prod
    namespace: default
  project: default
  source:
    path: helm
    repoURL: https://github.com/adavarski/ArgoCD-GitOps-playground
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-prod.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
