# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      id: dockerhub-login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build, tag, and push image to DockerHub
      id: build-image
      run: |
        # Build a docker container and push it to DockerHub
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build -t davarski/gitops-demo:${GITHUB_REF##*/}-$git_hash .
        echo "Pushing image to DockeHub..."
        docker push davarski/gitops-demo:${GITHUB_REF##*/}-$git_hash
        
    - name: Update Version
      run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          version=$(cat ./helm/values.yaml | grep version: | awk '{print $2}')
          sed -i "s/$version/${GITHUB_REF##*/}-$git_hash/" ./helm/values.yaml
          
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.ARGOCD }}
        commit_message: Version updated
