name: release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: davarski/gitops-demo
          tags: |
            type=ref,event=tag
          flavor: |
            latest=false
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Update Version
        run: |
            TMP=${{ steps.meta.outputs.tags }}
            TAG=${echo $TMP | cut -d : -f 2
            version=$(cat ./helm/values-prod.yaml | grep version: | awk '{print $2}')
            echo ${version}
            echo ${TAG}
            sed -i "s/$version/$TAG/" ./helm/values-prod.yaml
          
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.ARGOCD }}
          commit_message: Version updated
