# This is a basic workflow to help you get started with Actions

name: Release
 
on:
  release:
    types:
      - released

jobs:
  build:
    name: Build and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      id: dockerhub-login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build, tag, and push image to DockerHub
      id: build-image
      run: |
        # Build a docker container and push it to DockerHub
        release=${{ github.event.release.tag_name }}
        docker build -t davarski/gitops-demo:$release .
        echo "Pushing image to DockeHub..."
        docker push davarski/gitops-demo:$release
        
    - name: Update Version
      run: |
          release=${{ github.event.release.tag_name }}
          version=$(cat ./helm/values-prod.yaml | grep version: | awk '{print $2}')
          sed -i "s/$version/$release/" ./helm/values-prod.yaml
          
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.ARGOCD }}
        commit_message: Version updated
