# This is a basic workflow to help you get started with Actions

name: Release
 
on:
  release:
    types:
      - released

jobs:
  build:
    name: Build and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      id: dockerhub-login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
         push: true
         file: ./Dockerfile
         tags: davarski/gitops-demo:${{ github.event.release.tag_name }}
         build-args: VER=${{ github.event.release.tag_name }}
        
    - name: Update Version
      run: |
          VER=${{ github.event.release.tag_name }}
          version=$(cat ./helm/values-prod.yaml | grep version: | awk '{print $2}')
          sed -i "s/$version/$VER/" ./helm/values-prod.yaml
          
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.ARGOCD }}
        commit_message: Version updated
